print ("hello programing")
print ("my name is Ahmed")
print ("I am learning python") 
print ("I am student in AI & Data Engeniring")
print (" my age is 19 years old")
print (type (19))
print (type ("Ahmed"))
print("my hight is 1.89")
print (type (1.89))
print (type (True)) 